@startuml


|Администратор|
|#AntiqueWhite|Пользователь|
start
:Открывает главную страницу приложения;

if (Сервис дашбордов доступен) then (Да)
  if (Есть опубликованные дашборды) then (Да)
    |Пользователь|
    :Видит список дашбордов;
    :Видит первый дашборд;
    end
  else (Нет)
    |Пользователь|
    :Ошибка: Дашборды не найдены;
  endif

  |Администратор|
  :Открывает конструктор;
  :Создает дашборд;
  :Выбирает источники данных;
  :Выбирает тип визуализации;
  :Добавляет фильтры;
  :Размещает виджет;
  :Кастомизирует виджет;
  :Сохраняет изменения;
  :Создает публичную ссылку;

  |Пользователь|
  :Видит список дашбордов;
  :Видит первый дашборд;
  :Применяет фильтры к данным виджета;
  :Фильтры применяются к виджету;
  :Нажимает кнопку экспорта;
  :Выбирает формат файла;
  :Скачивание файла;
  :Нажимает кнопку Сгенерировать вывод;

  if (ИИ-сервис доступен) then (Да)
    :Видит сгенерированный вывод;
    :Нажимает кнопку Копировать;
    :Текст скопирован в буфер обмена;
  else (Нет)
    :Ошибка;
    end
  endif

  |Администратор|
  :Выбирает виджет;
  :Удаляет фильтры виджета;
  :Сохраняет изменения;

  |Пользователь|
  :Применяет фильтры к данным виджета;
  :Ошибка;

  |Администратор|
  :Удаляет публичную ссылку;

  |Пользователь|
  :Обновляет дашборд;
  :Ошибка: Дашборд не найден;

else (Нет)
  |Пользователь|
  :Ошибка: Сервис временно недоступен;
  stop
endif


stop

@enduml
