FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

COPY Dashboards.sln .
COPY Dashboards/Dashboards.csproj Dashboards/

RUN dotnet restore Dashboards/Dashboards.csproj

COPY . .

WORKDIR /app/Dashboards

EXPOSE 8080
CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080"]
