// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UniDashDbContext))]
    [Migration("20250719103202_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AcademicState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AcademicState", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.AddressState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressState", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefit", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Citizenship", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.EducationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationProgram", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.EducationStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationStandard", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Faculty", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organization", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressStateId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Ball")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("BenefitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Budget")
                        .HasColumnType("text");

                    b.Property<Guid>("CitizenshipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ContingentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Course")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EducationProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EducationStandardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentExternalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudyFormId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicStateId");

                    b.HasIndex("AddressStateId");

                    b.HasIndex("BenefitId");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("ContingentDate");

                    b.HasIndex("EducationProgramId");

                    b.HasIndex("EducationStandardId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StudentExternalId");

                    b.HasIndex("StudyFormId");

                    b.HasIndex("StudentExternalId", "ContingentDate")
                        .IsUnique();

                    b.ToTable("Student", "university");
                });

            modelBuilder.Entity("Domain.Entities.StudyForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyForm", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasOne("Domain.Entities.AcademicState", "AcademicState")
                        .WithMany("Students")
                        .HasForeignKey("AcademicStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AddressState", "AddressState")
                        .WithMany("Students")
                        .HasForeignKey("AddressStateId");

                    b.HasOne("Domain.Entities.Benefit", "Benefit")
                        .WithMany("Students")
                        .HasForeignKey("BenefitId");

                    b.HasOne("Domain.Entities.Citizenship", "Citizenship")
                        .WithMany("Students")
                        .HasForeignKey("CitizenshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EducationProgram", "EducationProgram")
                        .WithMany("Students")
                        .HasForeignKey("EducationProgramId");

                    b.HasOne("Domain.Entities.EducationStandard", "EducationStandard")
                        .WithMany("Students")
                        .HasForeignKey("EducationStandardId");

                    b.HasOne("Domain.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("Students")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Domain.Entities.StudyForm", "StudyForm")
                        .WithMany("Students")
                        .HasForeignKey("StudyFormId");

                    b.Navigation("AcademicState");

                    b.Navigation("AddressState");

                    b.Navigation("Benefit");

                    b.Navigation("Citizenship");

                    b.Navigation("EducationProgram");

                    b.Navigation("EducationStandard");

                    b.Navigation("Faculty");

                    b.Navigation("Organization");

                    b.Navigation("StudyForm");
                });

            modelBuilder.Entity("Domain.Entities.AcademicState", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.AddressState", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Benefit", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.EducationProgram", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.EducationStandard", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.StudyForm", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
