// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UniDashDbContext))]
    [Migration("20260227190216_AddDisciplinesTable")]
    partial class AddDisciplinesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AcademicState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AcademicState", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Achivment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Achivment", "university");
                });

            modelBuilder.Entity("Domain.Entities.AchivmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AchivmentCategory", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.AddressState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressState", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Benefit", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Branch", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Citizenship", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.ContingentStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressStateId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Ball")
                        .HasColumnType("double precision");

                    b.Property<string>("Budget")
                        .HasColumnType("text");

                    b.Property<DateTime>("ContingentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Course")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicStateId");

                    b.HasIndex("AddressStateId");

                    b.HasIndex("ContingentDate");

                    b.HasIndex("StudentExternalId");

                    b.HasIndex("StudentExternalId", "ContingentDate")
                        .IsUnique();

                    b.ToTable("ContingentStudent", "university");
                });

            modelBuilder.Entity("Domain.Entities.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Discipline", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.EducationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationProgram", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.EducationStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationStandard", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Faculty", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Order", "university");
                });

            modelBuilder.Entity("Domain.Entities.OrderCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderCategory", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organization", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BenefitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EducationProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EducationStandardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudyFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainingLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("EducationProgramId");

                    b.HasIndex("EducationStandardId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StudyFormId");

                    b.HasIndex("TrainingLevelId");

                    b.ToTable("Student", "university");
                });

            modelBuilder.Entity("Domain.Entities.StudyForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyForm", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.TrainingLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TrainingLevel", "dictionary");
                });

            modelBuilder.Entity("Domain.Entities.Achivment", b =>
                {
                    b.HasOne("Domain.Entities.AchivmentCategory", "Category")
                        .WithMany("Achivments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("Achivments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.ContingentStudent", b =>
                {
                    b.HasOne("Domain.Entities.AcademicState", "AcademicState")
                        .WithMany("Students")
                        .HasForeignKey("AcademicStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AddressState", "AddressState")
                        .WithMany("Students")
                        .HasForeignKey("AddressStateId");

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("ContingentStudents")
                        .HasForeignKey("StudentExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicState");

                    b.Navigation("AddressState");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.OrderCategory", "Category")
                        .WithMany("Orders")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("Orders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasOne("Domain.Entities.Benefit", "Benefit")
                        .WithMany("Students")
                        .HasForeignKey("BenefitId");

                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany("Students")
                        .HasForeignKey("BranchId");

                    b.HasOne("Domain.Entities.Citizenship", "Citizenship")
                        .WithMany("Students")
                        .HasForeignKey("CitizenshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EducationProgram", "EducationProgram")
                        .WithMany("Students")
                        .HasForeignKey("EducationProgramId");

                    b.HasOne("Domain.Entities.EducationStandard", "EducationStandard")
                        .WithMany("Students")
                        .HasForeignKey("EducationStandardId");

                    b.HasOne("Domain.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("Students")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Domain.Entities.StudyForm", "StudyForm")
                        .WithMany("Students")
                        .HasForeignKey("StudyFormId");

                    b.HasOne("Domain.Entities.TrainingLevel", "TrainingLevel")
                        .WithMany("Students")
                        .HasForeignKey("TrainingLevelId");

                    b.Navigation("Benefit");

                    b.Navigation("Branch");

                    b.Navigation("Citizenship");

                    b.Navigation("EducationProgram");

                    b.Navigation("EducationStandard");

                    b.Navigation("Faculty");

                    b.Navigation("Organization");

                    b.Navigation("StudyForm");

                    b.Navigation("TrainingLevel");
                });

            modelBuilder.Entity("Domain.Entities.AcademicState", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.AchivmentCategory", b =>
                {
                    b.Navigation("Achivments");
                });

            modelBuilder.Entity("Domain.Entities.AddressState", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Benefit", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Citizenship", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.EducationProgram", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.EducationStandard", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.OrderCategory", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("Achivments");

                    b.Navigation("ContingentStudents");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.StudyForm", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.TrainingLevel", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
